# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f49c33316b79331ff5bd752a58deadbb8fb98f3c0fb3877d720248f6c95147aa7bf8704f31f9a7f2425856d6aad48fbf3ac635c2ca45467cdc47678bf8055a2

test:
  secret_key_base: e29bd5ce03181602cc6532c106121801803a5372dcc3bcc2d63fead797d3a1263b7cda6273f0e9c277748bfaafc472f03891b0cc22e1c1033528bdd0c24a6df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
